/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_demo_lbs_myndk_EchoClientActivity */

#ifndef _Included_com_demo_lbs_myndk_EchoClientActivity
#define _Included_com_demo_lbs_myndk_EchoClientActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_lbs_myndk_EchoClientActivity
 * Method:    nativestartTcpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_demo_lbs_myndk_EchoClientActivity_nativestartTcpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
